### ISSUE TITLE
2FA doesn't run on Paper 1.20.5+

### ISSUE THREAD

**Issue by Geitenijs** [LielAmar/2FA#165] opened 2024-08-01 10:50 UTC
**Describe the bug**
2FA doesn't work on Paper 1.20.5 or newer as they've changed the way you need to check for the server version. It should work fine when using Bukkit.getServer().getBukkitVersion()

**Screenshots and Videos**
https://pastebin.com/Xk8h39Fi

**Server Information**

 - OS: Debian 12
 - Java Version: 21
 - Server Game Version: Paper 1.21
 - Plugin Version: 1.7.1

**Comment by DirtyConcept** [comment] 2024-08-01 15:19
I'll test this issue in the 1.7.2 dev builds again, which hopefully shouldn't happen since I've already fixed the versioning detection on all versions with x.y format without the 3rd z digit. (x.y.z -> 1.21.0 which used to be detected like that, but now it detects it as x.y -> 1.21)

**Comment by DirtyConcept** [comment] 2024-08-01 15:24
The issue is already fixed in the 1.7.2 version. @LielAmar will release it to Spigot whenever he gets available, in the meantime I can upload that to the GitHub releases for you to run. :)

**Closed by DirtyConcept** 2024-08-01 15:24 UTC
Labels: bug

**Comment by Geitenijs** [comment] 2024-08-01 15:27
> The issue is already fixed in the 1.7.2 version. @LielAmar will release it to Spigot whenever he gets available, in the meantime I can upload that to the GitHub releases for you to run. :)

Great! That’d be amazing :)
Thanks for your help

**Comment by DirtyConcept** [comment] 2024-08-01 15:41
> > The issue is already fixed in the 1.7.2 version. @LielAmar will release it to Spigot whenever he gets available, in the meantime I can upload that to the GitHub releases for you to run. :)
> 
> Great! That’d be amazing :) Thanks for your help

I've uploaded it as a Github release for now until LielAmar uploads it to spigot, so you could download that from there :)
